Resources:
  kubevpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: KubeVPC
          Value: Kubernetes
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref kubevpc
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGatewaykube
      VpcId: !Ref kubevpc
  InternetGatewaykube:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: KubeVPC
          Value: Kubernetes
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref kubevpc
      CidrBlock: 10.0.2.0/24
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref kubevpc
      Tags:
        - Key: route
          Value: public
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewaykube
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref kubevpc
      Tags:
        - Key: route
          Value: private
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  EC2SSMROLE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2SSMpolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 
              - ssm:GetParameter
              - ssm:PutParameter
            Resource: '*'
      Roles: 
        - !Ref EC2SSMROLE
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2SSMROLE
  controllernode:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}"
      InstanceType: t2.medium
      KeyName: controller-node
      SourceDestCheck: false
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref PublicSecurityGroup
          SubnetId: !Ref PublicSubnet
          PrivateIpAddress: 10.0.1.174
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -eux

          export DEBIAN_FRONTEND=noninteractive

          # Update packages
          apt-get update

          #installing git
          apt install git 
          git clone https://github.com/HARSHAVARDHINISM/aws-k8s-cluster.git

          chmod +x aws-k8s-cluster/master.sh
          bash aws-k8s-cluster/master.sh

  PrivateRoute:
    Type: AWS::EC2::Route
    DependsOn: controllernode
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      InstanceId: !Ref controllernode
  Node1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}"
      InstanceType: t2.small
      KeyName: controller-node
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: "0"
          GroupSet:
            - !Ref PrivateSecurityGroup
          SubnetId: !Ref PrivateSubnet
          PrivateIpAddress: 10.0.2.211
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -eux

          export DEBIAN_FRONTEND=noninteractive

          
          apt-get update
          apt install git -y

          git clone https://github.com/HARSHAVARDHINISM/aws-k8s-cluster.git
          chmod +x aws-k8s-cluster/worker1.sh
          bash aws-k8s-cluster/worker1.sh

          
  Node2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}"
      InstanceType: t2.small
      KeyName: controller-node
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: "0"
          GroupSet:
            - !Ref PrivateSecurityGroup
          SubnetId: !Ref PrivateSubnet
          PrivateIpAddress: 10.0.2.167
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -eux

          export DEBIAN_FRONTEND=noninteractive

          apt-get update
          apt install git -y 
          git clone https://github.com/HARSHAVARDHINISM/aws-k8s-cluster.git
          chmod +x aws-k8s-cluster/worker2.sh
          bash aws-k8s-cluster/worker2.sh
          
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Publicsecuritygroup
      VpcId: !Ref kubevpc
      SecurityGroupIngress:
        # SSH from your laptop
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 49.207.217.69/32

        # Allow all traffic from within the VPC
        - IpProtocol: -1
          CidrIp: 10.0.0.0/16

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Privatesecuritygroup
      VpcId: !Ref kubevpc
      SecurityGroupIngress:
        # Allow all traffic from the Controller/NAT SG
        - IpProtocol: -1
          CidrIp: 10.0.1.0/24

        # Allow communication between worker nodes
        - IpProtocol: -1
          CidrIp: 10.0.2.0/24

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
